Feature Branch
rsundar/weather-app pull request #2
Opened 2020-10-30 22:46 UTC by rsundar

This project is incomplete but the core functionality is done

# FEATURES CREATED

* Form where user can enter their city for which they wish to check the weather.
* Can pull weather data from openweathermap api.

# TODO

* Add a geolocation api to automatically detect the location.
* Create the UI using bulma
* Create a chart of the hourly forecast for the next 24 hours.

2020-10-30 23:14 UTC, lucasmazo23 requested changes
## Changes required 🔧
### You are doing a great job so far, and the project is looking good.

### For the project to get approved kindly implement these changes:

### Required changes:
- [ ] [REQUIRED] The app should change its appearance based on the results from the search
![image](https://user-images.githubusercontent.com/73254040/97763653-da6d1100-1ad1-11eb-9df6-cca7a42fdf55.png)
[source](https://www.theodinproject.com/courses/javascript/lessons/weather-app)
- [ ] [REQUIRED] Try to use ES6 suntax when possible, `const myFunc = () => {}` instead of `function myFunc(){}` (examples in my comments below)
![image](https://user-images.githubusercontent.com/73254040/97763962-c4ac1b80-1ad2-11eb-9883-cc267723d109.png)
[Source](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/)

### Happy coding! 💻
## Lucas Mazo

2020-10-30 23:14 UTC, lucasmazo23 commented on src/modules/fetch.js
> +export default async function retrieveData(city, metric) {
![image](https://user-images.githubusercontent.com/73254040/97764065-0e950180-1ad3-11eb-9197-46d461753535.png)

2020-10-30 23:14 UTC, lucasmazo23 commented on src/modules/index.js
>  function showData(weatherData) {
![image](https://user-images.githubusercontent.com/73254040/97764118-32584780-1ad3-11eb-99ad-0e6823ccd191.png)

2020-10-30 23:14 UTC, lucasmazo23 commented on src/modules/index.js
> +  if (document.forms.cityForm.i.checked) {
[OPTIONAL] Consider using object destructuring

![image](https://user-images.githubusercontent.com/73254040/97764163-4e5be900-1ad3-11eb-9ba5-c174a63a57c0.png)

2020-11-09 20:46 UTC, rsundar commented on src/modules/index.js
>  function showData(weatherData) {
done

2020-11-09 20:46 UTC, rsundar commented on src/modules/fetch.js
> +export default async function retrieveData(city, metric) {
done

2020-11-11 23:14 UTC, rOluochKe requested changes
Hello @rsundar 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Fix the conflict in the pull request, see the image below for the specific file
![conflict](https://user-images.githubusercontent.com/8114528/98875218-c8ee1680-248c-11eb-9bb5-8120f1e7d75a.png)
### Make the change and submit for another code review. Good luck.
- Happy coding!

2020-11-17 23:02 UTC, rsundar commented
# CHANGES MADE
- Made the changes as required by @lucasmazo23 and @rOluochKe 
- The app changes the picture depending on the weather condition and city.

I will add the charting facility of the hourly forecast later as an improvement.

2020-11-17 23:55 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi  @rsundar! Your effort to work on the feedback from the last reviews is commendable! :+1: There are a few details to work on to complete this project though:
- [x] Linters config: Your linter checks are not running. Please reconfigure linting for your repository. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)). Make use of the [config files](https://github.com/microverseinc/linters-config/tree/master/javascript) prepared for this section.
- [x] Nice job implementing a descriptive README. However, your live demo link doesn't lead to a deployed version of your app. Please fix this.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-11-18 16:49 UTC, Dandush03 approved these changes
# Status :rocket: Approved
# Great Work Implementing Necessary Changes
# Happy Coding :computer:

2020-11-18 16:50 UTC, merged